version: '3.7'

services:
  nodejs:
    restart: unless-stopped
    container_name: nodejs
    build:
      context: .
      target: development
    # command: sh migration.sh
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - network

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    networks:
      - network
    volumes:
      - ./db-data:/data/db

networks:
  network:
    driver: bridge